CMake: use CMAKE_C_STANDARD to set C standard
Commit d95b30a08a96 ("CMake: bump minimum required version to 3.10")
bumped the minium required CMake version from 2.8.12 to 3.10, we can use
the CMAKE_C_STANDARD property to set the C standard.

This results in the gnu99 standard being used, which is needed to fix
the following clang-tidy errors:

/home/stijn/projects/vallumd/src/mosquitto.c:22:38: error: call to undeclared function 'strsep'; ISO C99 and later do not support implicit function declarations [clang-diagnostic-implicit-function-declaration]
   22 |         parsed_topic.action = strdup(strsep(&topic, "/"));
      |                                      ^

/home/stijn/projects/vallumd/src/mosquitto.c:77:5: error: call to undeclared function 'gethostname'; ISO C99 and later do not support implicit function declarations [clang-diagnostic-implicit-function-declaration]
   77 |     gethostname(hostname, 15);
      |     ^

Fixes: da61ce98e861 ("mosquitto: generate client id")
Fixes: 47d3a6b01fb0 ("mosquitto: add function to parse topic")
Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>